spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/data.sql
spring.sql.init.schema-locations=classpath:/schema.sql
spring.datasource.url=jdbc:mysql://localhost:3306/http-service-watcher-db
spring.datasource.username=alaz
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

http-service-watcher.cfg.scheduler.initial_wait_in_ms=1000
http-service-watcher.cfg.scheduler.run_interval_in_ms=15000
http-service-watcher.cfg.scheduler.service_time_out_in_ms=10000
